### ISSUE TITLE
Class 'Fruitware\VictoriaBankGateway\VictoriaBank\Request' not found

### ISSUE THREAD

**Issue by alexminza** [Fruitware/VictoriaBankGateway#1]
When initializing the gateway client according to the demo code from [README.md](https://github.com/Fruitware/VictoriaBankGateway/blob/master/README.md) using manual procedure an unhandled exception is thrown:

1. Installation - via composer
2. Step 2. Init Gateway client
3. Init Gateway client manually
4. calling VictoriaBankGateway->setSecurityOptions

`Fatal error: Uncaught Error: Class 'Fruitware\VictoriaBankGateway\VictoriaBank\Request' not found in .../vendor/fruitware/victoria-bank-gateway/src/`[VictoriaBankGateway.php:334](https://github.com/Fruitware/VictoriaBankGateway/blob/master/src/VictoriaBankGateway.php#L334)

`Stack trace: Fruitware\VictoriaBankGateway\VictoriaBankGateway->setSecurityOptions(...`

**Comment by ruscon** [comment]
thx

**Comment by alexminza** [comment]
Thanks to @eugentorica for spotting this!
