### ISSUE TITLE
Allow setting test gateway url

### ISSUE THREAD

**Issue by alexminza** [Fruitware/VictoriaBankGateway#7]
Victoriabank have introduced a test gateway for new clients to test and debug their integrations before going live with the current production gateway: `https://ecomt.victoriabank.md/cgi-bin/cgi_link`

To allow users to use the new test gateway a new option to set the gateway url should be introduced.

At the `VictoriaBankGateway` class level? `VictoriaBankGateway->setGatewayUrl(gatewayUrl)`

**Comment by alexminza** [comment]
@ruscon have a look at this 
- https://github.com/alexminza/VictoriaBankGateway/tree/GatewayUrl
- https://github.com/alexminza/VictoriaBankGateway/commits/GatewayUrl

**Comment by keriat** [comment]
Looks nice, thank you. 👍
I'll approve it. 

**On a side note** 
I've checked your [plugin for WooCommerce](https://ru.wordpress.org/plugins/wc-victoriabank/) base on our library — faced it in one of the support requests from clients.
Didn't see any reference to this lib 😞
_Don't get me wrong — it's not about being vainglory or money — you can use the plugin and receive. contributions — it's not an object of discussion anyway._
But linking us, this lib and GitHub URL will definitely help to improve it and make it more like a industry-grade product — not just a quick share of the internal working code.
So, would you be so kind and refer to library in the description of you plugin? 

👌 Thanks in advance and no offense (hopefully you'll get me right).

**Comment by alexminza** [comment]
@keriat it is proudly mentioned in the source code of the plugin:

https://github.com/alexminza/wc-victoriabank/blob/master/wc-victoriabank.php
> //This plugin is based on VictoriaBankGateway by Fruitware https://github.com/Fruitware/VictoriaBankGateway (https://packagist.org/packages/fruitware/victoria-bank-gateway)

Do you mean also adding a mention in the plugin readme.txt?
